apiVersion: apps/v1
kind: Deployment
metadata:
  name: datadog-mongo
  namespace: datadog-app
  labels:
    app: datadog-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datadog-mongo
  template:
    metadata:
      labels:
        app: datadog-mongo
    spec:
      containers:
      - name: mongo
        image: mongo
        ports:
        - name: mongo-port
          containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-svc
  namespace: datadog-app
spec:
  type: NodePort
  selector:
    app: datadog-mongo
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 27017
      targetPort: 27017